### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Rudloff** [juankysoriano/Zen#5]
Hello,

Would you be interested in publishing this app on [F-Droid](https://f-droid.org/)?

**Comment by juankysoriano** [comment]
Sure, sorry for the late reply. 

Can you explain a bit more about what does this involve?

**Comment by Rudloff** [comment]
Sorry for not explaining more.
We make sure the apps are open source and then write a recipe that builds releases automatically from source and publish them in our index. Then, users can install them with the F-Droid client.
(You can find more information about the whole process [here](https://f-droid.org/en/docs/FAQ_-_App_Developers).)

Your app seems to already comply with [our inclusion policy](https://f-droid.org/en/docs/Inclusion_Policy/) so all we would need is your approval.

**Comment by juankysoriano** [comment]
you have my approval

**Comment by juankysoriano** [comment]
Ok, you have my approval
